### ISSUE TITLE
Use of unstable library feature 'once_cell_try' in newer nightly

### ISSUE THREAD

**Issue by Dr-Emann** [OpenByteDev/dll-syringe#11] opened 2023-04-07 19:46 UTC
See https://github.com/rust-lang/rust/issues/109737 for discussion, it appears the `once_cell` feature was split, `once_cell` has been stabilized, `once_cell_try` has been added for the try methods

**Comment by OpenByteDev** [comment] 2023-04-07 22:54
Duplicate of #10

**Closed by OpenByteDev** 2023-04-07 22:54 UTC
